### ISSUE TITLE
Vanilla checkout does not build

### ISSUE THREAD

**Issue by toffebjorkskog** [generoi/sage#1]
On branch Timber

assets/styles/common/_global.scss
Error: Undefined variable: "$spacing".
        on line 14 of assets/styles/common/_global.scss

> > ```
> > .spacing { margin: $spacing; }
> > ```
> > 
> >    -----------------------^

**Comment by toffebjorkskog** [comment]
Fixed it via https://github.com/generoi/sage/commit/be7dd0f5445a37be6cc03b301a89a639fde4c34f
the variable needed outside the it/else scope needs to be defined outside the scope.

http://stackoverflow.com/questions/15371332/sass-ignores-variables-defined-in-if-statement

**Comment by oxyc** [comment]
Hups undrar hur ajg missat det. Tyckte nog jag testade kompilera. Tack!
