### ISSUE TITLE
Instagram icon

### ISSUE THREAD

**Issue by petterw03** [generoi/sage#2]
I think the Instagram icon from [here](https://github.com/generoi/genero-new/blob/master/web/app/themes/generosage/assets/images/icons/instagram.svg) should be added to the default icons.

**Comment by oxyc** [comment]
Sure, go for it. Every site I setup I customize the icons either way. Nice to have some better defaults though.

**Comment by petterw03** [comment]
I think it makes sense since the default header.twig references to it :)
https://github.com/generoi/sage/blob/timber/templates/layout/header.twig#L77
