### ISSUE TITLE
TinyMCE editor scrolls down on every keystroke

### ISSUE THREAD

**Issue by petterw03** [generoi/sage#3]
Some weird bug with the theme is making the visual editor scroll down on every keystroke.

To replicate:
1. Activate our custom Sage theme
2. Edit a page using the Visual editor
3. Press any key

**Comment by oxyc** [comment]
Yeah, I usually disable TinyMCE autogrow feature. Same thing happens when autogrow is used in Drupal. Not sure if its caused on our end, but I dont think so, havent really researched it.

**Comment by toffebjorkskog** [comment]
Saw it on noolan after a clean install. Have seen it on some other projects as well.

**Comment by oxyc** [comment]
Fixed in https://github.com/generoi/sage/commit/83dce7ed56f21034a70da01ab17b55d1eedcd918
